// <auto-generated />
using Ling.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ling.Migrations
{
    [DbContext(typeof(LingDbContext))]
    [Migration("20181210205910_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ling.Models.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EnglishName");

                    b.Property<string>("ISOCode");

                    b.Property<string>("OriginalName");

                    b.Property<string>("Romanized");

                    b.HasKey("ID");

                    b.ToTable("Languages");

                    b.HasData(
                        new { ID = 1, EnglishName = "Mandarin", ISOCode = "cmn-Hans-CN", OriginalName = "官话", Romanized = "Guānhuà" },
                        new { ID = 2, EnglishName = "English", ISOCode = "en-US", OriginalName = "English" },
                        new { ID = 3, EnglishName = "Hindi", ISOCode = "hi-IN", OriginalName = "Hindī", Romanized = "हिन्दी " },
                        new { ID = 4, EnglishName = "Spanish (Spain)", ISOCode = "es-ES", OriginalName = "Español (España)", Romanized = "español" },
                        new { ID = 5, EnglishName = "Spanish", ISOCode = "es-MX", OriginalName = "Español", Romanized = "español, castellano" },
                        new { ID = 6, EnglishName = "Arabic (Egypt)", ISOCode = "ar-EG", OriginalName = "العربية", Romanized = "al-ʻarabiyyah" },
                        new { ID = 7, EnglishName = "Portuguese (Brazil)", ISOCode = "pt-BR", OriginalName = "Português (Brasil)", Romanized = "português" },
                        new { ID = 8, EnglishName = "Russian", ISOCode = "ru-RU", OriginalName = "русский язык", Romanized = "russkiy yazyk" },
                        new { ID = 9, EnglishName = "Bengali", ISOCode = "bn-IN", OriginalName = "বাংলা", Romanized = "Bangla" },
                        new { ID = 10, EnglishName = "French", ISOCode = "fr-FR", OriginalName = "français", Romanized = "français" },
                        new { ID = 11, EnglishName = "Japanese", ISOCode = "ja-JP", OriginalName = "日本語", Romanized = "Nihongo" },
                        new { ID = 12, EnglishName = "Malay", ISOCode = "ms-MY", OriginalName = "بهاس ملايو‎", Romanized = "Bahasa Melayu" }
                    );
                });

            modelBuilder.Entity("Ling.Models.Recording", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlternateLanguages");

                    b.Property<byte>("Audio");

                    b.Property<int>("LanguageID");

                    b.Property<decimal>("Length");

                    b.HasKey("ID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("Ling.Models.Recording", b =>
                {
                    b.HasOne("Ling.Models.Language", "Language")
                        .WithMany("Recordings")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
